use_frameworks!
inhibit_all_warnings!

target 'MainPart' do
  platform :ios, '13.0'
  pod 'Moya'
  pod 'SnapKit'
  pod 'MBProgressHUD'
  pod 'R.swift'
end

target 'MainPart WatchKit App' do
  platform :watchos, '6.0'
end

target 'MainPart WatchKit Extension' do
  platform :watchos, '6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5'
    end
  end
end
